# Generated by Django 4.2.2 on 2024-03-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('University', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('session', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
